Query ffmpeg version in s6 run script instead of subprocessing in every import

diff --git a/docker/rootfs/etc/s6-overlay/s6-rc.d/frigate/run b/docker/rootfs/etc/s6-overlay/s6-rc.d/frigate/run
--- a/docker/rootfs/etc/s6-overlay/s6-rc.d/frigate/run
+++ b/docker/rootfs/etc/s6-overlay/s6-rc.d/frigate/run
@@ -42,6 +42,8 @@ function migrate_db_path() {
     fi
 }
 
+LIBAVFORMAT_VERSION_MAJOR=$(ffmpeg -version | grep -Po 'libavformat\W+\K\d+') || echo "[ERROR] Failed to determine ffmpeg version"
+
 echo "[INFO] Preparing Frigate..."
 migrate_db_path
 
